version: '3.8'

services:
  
  core-analysis:
    build: ./service_core_analysis
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=core-analysis
      - SERVICE_PORT=8000
    volumes:
      - ./shared_data:/app/shared_data
    networks:
      - review-analysis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  export:
    build: ./service_exporter
    ports:
      - "8001:8000"
    environment:
      - SERVICE_NAME=export
      - SERVICE_PORT=8000
    volumes:
      - ./shared_data:/app/shared_data
      - ./exports:/app/exports
    depends_on:
      - core-analysis
    networks:
      - review-analysis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  demo-ui:
    build: ./service_demo_ui
    ports:
      - "8501:8501"
    environment:
      - SERVICE_NAME=demo-ui
      - CORE_ANALYSIS_URL=http://core-analysis:8000
      - EXPORT_URL=http://export:8000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./shared_data:/app/shared_data
      - ./exports:/app/exports
    depends_on:
      core-analysis:
        condition: service_healthy
      export:
        condition: service_healthy
    networks:
      - review-analysis-network
    restart: unless-stopped

networks:
  review-analysis-network:
    driver: bridge

volumes:
  shared_data:
  exports: